services:
  tck-container:
    build:
      context: .
      dockerfile: tck.dockerfile
    environment:
      NUGET_PACKAGES: /var/tmp/nuget-packages
      NUGET_XMLDOC_MODE: ''
    volumes:
      - nuget-packages:/var/tmp/nuget-packages

volumes:
  nuget-packages:
