name: asciisharp

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kroki
    networks:
      - kroki

  kroki:
    image: yuzutech/kroki
    environment:
      KROKI_MERMAID_HOST: kroki-mermaid
    networks:
      - kroki
      - kroki-internal
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: unless-stopped

  kroki-mermaid:
    image: yuzutech/kroki-mermaid
    networks:
      - kroki-internal
    expose:
      - 8002
    restart: unless-stopped

networks:
  kroki:
  kroki-internal:
    internal: true
