name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      security-events: write
      packages: read
      actions: read

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
      with:
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Restore dependencies
      run: dotnet restore --locked-mode

    - name: Initialize CodeQL
      uses: github/codeql-action/init@b20883b0cd1f46c72ae0ba6d1090936928f9fa30 # v4.32.0
      with:
        languages: csharp
        build-mode: manual
        analysis-kinds: code-scanning,code-quality
        config-file: .github/codeql/config.yml

    - name: Build
      run: dotnet build --no-restore --no-incremental --nologo

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@b20883b0cd1f46c72ae0ba6d1090936928f9fa30 # v4.32.0
      with:
        category: /language:csharp

    - name: Test
      id: test
      run: dotnet test --no-restore --no-build --no-banner --no-ansi --no-progress --no-launch-profile --report-trx --coverage --coverage-output-format cobertura --results-directory artifacts/TestResults

    - name: Shutdown build servers
      if: always()
      run: dotnet build-server shutdown

    - name: Publish test reports
      uses: bibipkins/dotnet-test-reporter@5bafb08d6d3a2a779a0be59537305b0a92313f84 # v1.6.1
      if: ${{ steps.test.outcome == 'success' || steps.test.outcome == 'failure' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        results-path: artifacts/TestResults/*.trx
        coverage-path: artifacts/TestResults/*.cobertura.xml
        coverage-type: cobertura
        pull-request-check: true
